language: go

go:
- release

services:
- docker

env:
- CGO_ENABLED=0 GOOS=linux

script:
- cp $GOPATH/bin/gobench .
- docker build -t vitkhab/gobench:latest .

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  docker push vitkhab/gobench;
  fi